# language: ru
# encoding: utf-8
#parent uf:
@UF8_Turbo_Gherkin
#parent ua:
@UA23_Использовать_условия_в_сценариях

@IgnoreOnOFBuilds
@IgnoreOn82Builds
@IgnoreOnWeb


@tree



Функциональность: Проверка работы попытки исключения

Контекст: 
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий



Сценарий: Проверка, когда в попытке исключение только одна строка с истинным условием
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения15"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                        | 'Статус'  |
			| 'ПроверкаПопыткиИсключения15.feature'                                 | ''        |
			| 'ПроверкаПопыткиИсключения15'                                         | ''        |
			| 'ПроверкаПопыткиИсключения15'                                         | 'Success' |
			| '*Попытка 1'                                                          | ''        |
			| 'Попытка'                                                             | ''        |
			| 'Если "Число(1) = 1" Тогда'                                           | 'Success' |
			| 'Исключение'                                                          | ''        |
			| 'И Я запоминаю значение выражения \'1\' в переменную "ИмяПеременной"' | ''        |
			| '*Попытка 2'                                                          | ''        |
			| 'Попытка'                                                             | ''        |
			| 'И Я запоминаю значение выражения \'3\' в переменную "ИмяПеременной"' | 'Success' |
			| 'Исключение'                                                          | ''        |
			| 'И Я запоминаю значение выражения \'2\' в переменную "ИмяПеременной"' | ''        |
		
				
		


Сценарий: Проверка, когда в попытке исключение вызывается в шаге условия
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения14"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                        | 'Статус'  |
			| 'ПроверкаПопыткиИсключения14.feature'                                 | ''        |
			| 'ПроверкаПопыткиИсключения14'                                         | ''        |
			| 'ПроверкаПопыткиИсключения14'                                         | 'Success' |
			| '*Попытка 1'                                                          | ''        |
			| 'Попытка'                                                             | ''        |
			| 'Если "Число(kkk) = 1" Тогда'                                         | 'Success' |
			| 'И Я запоминаю в переменную "Test1" значение "01"'                    | ''        |
			| 'Исключение'                                                          | ''        |
			| 'И Я запоминаю значение выражения \'1\' в переменную "ИмяПеременной"' | 'Success' |
			| '*Попытка 2'                                                          | ''        |
			| 'Попытка'                                                             | ''        |
			| 'И я вывожу значение переменной "Test2"'                              | 'Success' |
			| 'Исключение'                                                          | ''        |
			| 'И Я запоминаю значение выражения \'2\' в переменную "ИмяПеременной"' | ''        |
		
		



Сценарий: Проверка когда в попытке идёт выполнение подсценария
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения12"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                           | 'Статус'  |
			| 'ПроверкаПопыткиИсключения12.feature'                                    | ''        |
			| 'ПроверкаПопыткиИсключения12'                                            | ''        |
			| 'ПроверкаПопыткиИсключения12'                                            | 'Success' |
			| 'Попытка'                                                                | ''        |
			| 'Дано Подсценарий для попытки один'                                      | ''        |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной0"' | 'Success' |
			| 'Исключение'                                                             | ''        |
			| 'Дано Подсценарий для попытки один'                                      | ''        |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной0"' | ''        |
		
		



Сценарий: Проверка когда в попытке падает асинхронный шаг
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения11"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"


		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                                                       | 'Статус'  |
			| 'ПроверкаПопыткиИсключения11.feature'                                                                | ''        |
			| 'ПроверкаПопыткиИсключения11'                                                                        | ''        |
			| 'ПроверкаПопыткиИсключения11'                                                                        | 'Success' |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной0"'                             | 'Success' |
			| 'И для каждой строки таблицы я выполняю'                                                             | 'Success' |
			| '\| \'Колонка1\' \|'                                                                                 | ''        |
			| '\| \'1\'        \|'                                                                                 | ''        |
			| '\| \'10\'       \|'                                                                                 | ''        |
			| 'Попытка'                                                                                            | ''        |
			| 'И Я запоминаю значение выражения \'Число($Колонка1$)*1\' в переменную "ИмяПеременной1"'             | 'Success' |
			| 'Затем я жду что в сообщениях пользователю будет подстрока "Нужное мне значение" в течение 2 секунд' | 'Success' |
			| 'И Я запоминаю значение выражения \'Число($Колонка1$)*2\' в переменную "ИмяПеременной2"'             | ''        |
			| 'Исключение'                                                                                         | ''        |
			| 'И Я запоминаю значение выражения \'Число($Колонка1$)*3\' в переменную "ИмяПеременной3"'             | 'Success' |
			| 'И я вывожу значение переменной "ИмяПеременной1"'                                                    | 'Success' |
			| 'И я вывожу значение переменной "ИмяПеременной2"'                                                    | 'Success' |
			| 'И я вывожу значение переменной "ИмяПеременной3"'                                                    | 'Success' |
			| 'И я запоминаю текст ошибки в переменную "ТекстОшибки"'                                              | 'Success' |
		
		Тогда в логе сообщений TestClient есть строки:
			| 'ИмяПеременной1 = 1'              |
			| 'ИмяПеременной2 = ИмяПеременной2' |
			| 'ИмяПеременной3 = 3'              |
			| 'ИмяПеременной1 = 10'             |
			| 'ИмяПеременной2 = ИмяПеременной2' |
			| 'ИмяПеременной3 = 30'             |
								
		И я нажимаю на кнопку с именем 'ПоказатьСкрытьТаблоПеременных'
		И в таблице "ТаблоПеременных" я разворачиваю строку:
			| 'Имя'      |
			| 'Контекст' |
		И в таблице "ТаблоПеременных" я перехожу к строке:
			| 'Значение'                                                                     | 'Имя'         |
			| 'Ожидали, что в сообщениях пользователю будет подстрока <Нужное мне значение>' | 'ТекстОшибки' |
				
		


Сценарий: Проверка когда две попытки исключения идут сразу друг за другом
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения10"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"

		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                              | 'Статус'  |
			| 'ПроверкаПопыткиИсключения10.feature'                                       | ''        |
			| 'ПроверкаПопыткиИсключения10'                                               | ''        |
			| 'ПроверкаПопыткиИсключения10'                                               | 'Success' |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'Попытка'                                                                   | ''        |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И Я запоминаю значение выражения \'11+11\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения1"'                                 | 'Success' |
			| 'И Я запоминаю значение выражения \'111+111\' в переменную "ИмяПеременной"' | ''        |
			| 'Исключение'                                                                | ''        |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'Попытка'                                                                   | ''        |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И Я запоминаю значение выражения \'22+22\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения2"'                                 | 'Success' |
			| 'И Я запоминаю значение выражения \'222+222\' в переменную "ИмяПеременной"' | ''        |
			| 'Исключение'                                                                | ''        |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"'     | 'Success' |
		
				
		
		



Сценарий: Проверка когда сценарий заканчивается словом исключение
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения9"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"


		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                              | 'Статус'  |
			| 'ПроверкаПопыткиИсключения9.feature'                                        | ''        |
			| 'ПроверкаПопыткиИсключения9'                                                | ''        |
			| 'ПроверкаПопыткиИсключения9_1'                                              | 'Success' |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'Попытка'                                                                   | ''        |
			| 'Попытка'                                                                   | ''        |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И Я запоминаю значение выражения \'11+11\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения1"'                                 | 'Success' |
			| 'Исключение'                                                                | ''        |
			| 'И Я запоминаю значение выражения \'3+3\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И Я запоминаю значение выражения \'33+33\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения2"'                                 | 'Success' |
			| 'И Я запоминаю значение выражения \'333+333\' в переменную "ИмяПеременной"' | ''        |
			| 'Исключение'                                                                | ''        |
			| 'ПроверкаПопыткиИсключения9_2'                                              | 'Success' |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'Попытка'                                                                   | ''        |
			| 'Попытка'                                                                   | ''        |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И Я запоминаю значение выражения \'11+11\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения1"'                                 | 'Success' |
			| 'Исключение'                                                                | ''        |
			| 'И Я запоминаю значение выражения \'3+3\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И Я запоминаю значение выражения \'33+33\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения2"'                                 | 'Success' |
			| 'И Я запоминаю значение выражения \'333+333\' в переменную "ИмяПеременной"' | ''        |
			| 'Исключение'                                                                | ''        |
		
				
				




Сценарий: Проверка работы попытки исключения. Вложенныые попытки исключения и исключения происходят в циклах
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения8"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
		Тогда в логе сообщений TestClient есть строки:
			|'ИмяПеременной = 4'|
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                              | 'Статус'  |
			| 'ПроверкаПопыткиИсключения8.feature'                                        | ''        |
			| 'ПроверкаПопыткиИсключения8'                                                | ''        |
			| 'ПроверкаПопыткиИсключения8'                                                | 'Success' |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'Попытка'                                                                   | ''        |
			| 'Попытка'                                                                   | ''        |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И Я запоминаю значение выражения \'11+11\' в переменную "ИмяПеременной"'   | 'Success' |
			| '*И группа шагов один'                                                      | ''        |
			| 'Если "Истина" Тогда'                                                       | 'Success' |
			| 'И я делаю 3 раз'                                                           | 'Success' |
			| 'И Я запоминаю значение выражения \'111+111\' в переменную "ИмяПеременной"' | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения1"'                                 | 'Success' |
			| 'И Я запоминаю значение выражения \'22+22\' в переменную "ИмяПеременной"'   | ''        |
			| 'И Я запоминаю значение выражения \'4+4\' в переменную "ИмяПеременной"'     | ''        |
			| 'Исключение'                                                                | ''        |
			| '*И группа в исключении 1'                                                  | ''        |
			| 'И Я запоминаю значение выражения \'3+3\' в переменную "ИмяПеременной"'     | 'Success' |
			| '*И группа в исключении 2'                                                  | ''        |
			| 'И Я запоминаю значение выражения \'33+33\' в переменную "ИмяПеременной"'   | 'Success' |
			| '*И группа шагов два'                                                       | ''        |
			| 'Если "Истина" Тогда'                                                       | 'Success' |
			| 'И я делаю 3 раз'                                                           | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения2"'                                 | 'Success' |
			| 'И Я запоминаю значение выражения \'5+5\' в переменную "ИмяПеременной"'     | ''        |
			| 'Исключение'                                                                | ''        |
			| '*И группа в исключении 3'                                                  | ''        |
			| 'И Я запоминаю значение выражения \'222+222\' в переменную "ИмяПеременной"' | 'Success' |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И я вывожу значение переменной "ИмяПеременной"'                            | 'Success' |
		
				



Сценарий: Проверка работы попытки исключения. Вложенныые попытки исключения и исключения происходят в условиях
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения7"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
		Тогда в логе сообщений TestClient есть строки:
			|'ИмяПеременной = 4'|
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                              | 'Статус'  |
			| 'ПроверкаПопыткиИсключения7.feature'                                        | ''        |
			| 'ПроверкаПопыткиИсключения7'                                                | ''        |
			| 'ПроверкаПопыткиИсключения7'                                                | 'Success' |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'Попытка'                                                                   | ''        |
			| 'Попытка'                                                                   | ''        |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И Я запоминаю значение выражения \'11+11\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'Если "Истина" Тогда'                                                       | 'Success' |
			| 'Если "Истина" Тогда'                                                       | 'Success' |
			| 'И Я запоминаю значение выражения \'111+111\' в переменную "ИмяПеременной"' | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения1"'                                 | 'Success' |
			| 'И Я запоминаю значение выражения \'22+22\' в переменную "ИмяПеременной"'   | ''        |
			| 'И Я запоминаю значение выражения \'4+4\' в переменную "ИмяПеременной"'     | ''        |
			| 'Исключение'                                                                | ''        |
			| 'И Я запоминаю значение выражения \'3+3\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И Я запоминаю значение выражения \'33+33\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'Если "Истина" Тогда'                                                       | 'Success' |
			| 'Если "Истина" Тогда'                                                       | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения2"'                                 | 'Success' |
			| 'И Я запоминаю значение выражения \'5+5\' в переменную "ИмяПеременной"'     | ''        |
			| 'Исключение'                                                                | ''        |
			| 'И Я запоминаю значение выражения \'222+222\' в переменную "ИмяПеременной"' | 'Success' |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"'     | 'Success' |
			| 'И я вывожу значение переменной "ИмяПеременной"'                            | 'Success' |
		
				





Сценарий: Проверка работы попытки исключения. Исключение внутри второй попытки исключения.
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения6"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
		Тогда в логе сообщений TestClient есть строки:
			|'ИмяПеременной = 4'|
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                            | 'Статус'  |
			| 'ПроверкаПопыткиИсключения6.feature'                                      | ''        |
			| 'ПроверкаПопыткиИсключения6'                                              | ''        |
			| 'ПроверкаПопыткиИсключения6'                                              | 'Success' |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'Попытка'                                                                 | ''        |
			| 'Попытка'                                                                 | ''        |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'И Я запоминаю значение выражения \'11+11\' в переменную "ИмяПеременной"' | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения1"'                               | 'Success' |
			| 'И Я запоминаю значение выражения \'4+4\' в переменную "ИмяПеременной"'   | ''        |
			| 'Исключение'                                                              | ''        |
			| 'И Я запоминаю значение выражения \'3+3\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'И Я запоминаю значение выражения \'33+33\' в переменную "ИмяПеременной"' | 'Success' |
			| 'И я вызываю исключение "ТекстИсключения2"'                               | 'Success' |
			| 'И Я запоминаю значение выражения \'5+5\' в переменную "ИмяПеременной"'   | ''        |
			| 'Исключение'                                                              | ''        |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"'   | 'Success' |
			| 'И я вывожу значение переменной "ИмяПеременной"'                          | 'Success' |
		
				

				
		





Сценарий: Проверка работы попытки исключения. Внутри попытки исключения ещё одна и ни одна не срабатывает
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения5"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
		Тогда в логе сообщений TestClient есть строки:
			|'ИмяПеременной = 4'|
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                          | 'Статус'  |
			| 'ПроверкаПопыткиИсключения5.feature'                                    | ''        |
			| 'ПроверкаПопыткиИсключения5'                                            | ''        |
			| 'ПроверкаПопыткиИсключения5'                                            | 'Success' |
			| 'И Я запоминаю значение выражения \'0+0\' в переменную "ИмяПеременной"' | 'Success' |
			| 'Попытка'                                                               | ''        |
			| 'Попытка'                                                               | ''        |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"' | 'Success' |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"' | 'Success' |
			| 'Исключение'                                                            | ''        |
			| 'И Я запоминаю значение выражения \'3+3\' в переменную "ИмяПеременной"' | ''        |
			| 'Исключение'                                                            | ''        |
			| 'И Я запоминаю значение выражения \'4+4\' в переменную "ИмяПеременной"' | ''        |
			| 'И я вывожу значение переменной "ИмяПеременной"'                        | 'Success' |
		
				
		
				
		



Сценарий: Проверка работы попытки исключения. Внутри попытки исключения ещё одна и срабатывает только внутренняя.
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения4"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
		Тогда в логе сообщений TestClient есть строки:
			|'ИмяПеременной = 4'|
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                          | 'Статус'  |
			| 'ПроверкаПопыткиИсключения4.feature'                                    | ''        |
			| 'ПроверкаПопыткиИсключения4'                                            | ''        |
			| 'ПроверкаПопыткиИсключения4'                                            | 'Success' |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"' | 'Success' |
			| 'Попытка'                                                               | ''        |
			| 'Попытка'                                                               | ''        |
			| 'И я вызываю исключение "Текст исключения"'                             | 'Success' |
			| 'И Я запоминаю значение выражения \'4+4\' в переменную "ИмяПеременной"' | ''        |
			| 'Исключение'                                                            | ''        |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"' | 'Success' |
			| 'Исключение'                                                            | ''        |
			| 'И Я запоминаю значение выражения \'3+3\' в переменную "ИмяПеременной"' | ''        |
			| 'И я вывожу значение переменной "ИмяПеременной"'                        | 'Success' |
		
		




Сценарий: Проверка работы попытки исключения. Внутри попытки не происходит вызов исключения
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения3"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
		Тогда в логе сообщений TestClient есть строки:
			|'ИмяПеременной = 4'|
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                          | 'Статус'  |
			| 'ПроверкаПопыткиИсключения3.feature'                                    | ''        |
			| 'ПроверкаПопыткиИсключения3'                                            | ''        |
			| 'ПроверкаПопыткиИсключения3'                                            | 'Success' |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"' | 'Success' |
			| 'Попытка'                                                               | ''        |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"' | 'Success' |
			| 'Исключение'                                                            | ''        |
			| 'И Я запоминаю значение выражения \'3+3\' в переменную "ИмяПеременной"' | ''        |
			| 'И я вывожу значение переменной "ИмяПеременной"'                        | 'Success' |
		
				

		
				
				


				



Сценарий: Проверка работы попытки исключения. В сценарии нет шагов в секции исключения.
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения2"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
		Тогда в логе сообщений TestClient есть строки:
			|'ИмяПеременной = 4'|
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                          | 'Статус'  |
			| 'ПроверкаПопыткиИсключения2.feature'                                    | ''        |
			| 'ПроверкаПопыткиИсключения2'                                            | ''        |
			| 'ПроверкаПопыткиИсключения2'                                            | 'Success' |
			| 'Попытка'                                                               | ''        |
			| 'И я вызываю исключение "Текст исключения"'                             | 'Success' |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"' | ''        |
			| 'Исключение'                                                            | ''        |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"' | 'Success' |
			| 'И я вывожу значение переменной "ИмяПеременной"'                        | 'Success' |
		
				
				
						


Сценарий: Проверка работы попытки исключения. В сценарии одно исключение.
	* Загрузка тестовой фичи
		Когда Я открываю VanessaAutomation в режиме TestClient со стандартной библиотекой
		И В поле с именем "КаталогФичСлужебный" я указываю путь к служебной фиче "ПроверкаПопыткиИсключения/ПроверкаПопыткиИсключения1"
		И Я нажимаю на кнопку перезагрузить сценарии в Vanessa-Automation TestClient
		И Я нажимаю на кнопку выполнить сценарии в Vanessa-Automation TestClient
	
	* Проверка результата
		Тогда в логе сообщений TestClient есть строки:
			|'ИмяПеременной = 4'|
				
		И я перехожу к закладке с именем "ГруппаСлужебная"
		И я нажимаю на кнопку с именем 'РазвернутьВсеСтрокиДереваСлужебный'
		И я перехожу к закладке с именем "ГруппаЗапускТестов"
		Тогда таблица "ДеревоТестов" стала равной:
			| 'Наименование'                                                          | 'Статус'  |
			| 'ПроверкаПопыткиИсключения1.feature'                                    | ''        |
			| 'ПроверкаПопыткиИсключения1'                                            | ''        |
			| 'ПроверкаПопыткиИсключения1'                                            | 'Success' |
			| 'Попытка'                                                               | ''        |
			| 'И я вызываю исключение "Текст исключения"'                             | 'Success' |
			| 'И Я запоминаю значение выражения \'1+1\' в переменную "ИмяПеременной"' | ''        |
			| 'Исключение'                                                            | ''        |
			| 'И Я запоминаю значение выражения \'2+2\' в переменную "ИмяПеременной"' | 'Success' |
			| 'И я запоминаю текст ошибки в переменную "ТекстОшибки"'                 | 'Success' |
			| 'И я вывожу значение переменной "ИмяПеременной"'                        | 'Success' |
		
		И я нажимаю на кнопку с именем 'ПоказатьСкрытьТаблоПеременных'
		И в таблице "ТаблоПеременных" я разворачиваю строку:
			| 'Имя'      |
			| 'Контекст' |
		И в таблице "ТаблоПеременных" я перехожу к строке:
			| 'Значение'         | 'Имя'         |
			| 'Текст исключения' | 'ТекстОшибки' |
						
						